pipeline {
    agent any


    environment {
        IMAGE_TAG = 'koduro/server'
        IMAGE_VERSION = 'latest'
    }

    stages {
        stage('Test') {
            steps {
                echo 'Test to see if the docker file exists'
                sh 'test -f project1/Dockerfile'
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'docker:20.10-dind'
                    args '--privileged'
                }
            }
            steps {
                echo 'Build the Docker image'
                sh '''
                    # Start the Docker daemon in the background
                    dockerd-entrypoint.sh &

                    # Wait a few seconds for the daemon to be ready
                    sleep 5

                    # Verify Docker is running
                    docker --version
                    docker info

                    # Build the image
                    docker build -t $IMAGE_TAG:$IMAGE_VERSION ./project1
                '''
            }
        }
    }
}
