pipeline {
    agent any


    environment {
        IMAGE_TAG = 'koduro/server'
        IMAGE_VERSION = 'latest'
    }

    stages {
        stage('Test') {
            steps {
                echo 'Test to see if the docker file exists'
                sh 'test -f project1/Dockerfile'
            }
        }
        stage('Build') {
            agent {
               docker {
                    image 'docker:20.10'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                    reuseNode true
                }
            }
            steps {
                echo 'Build the images if the dockerFile exits'
                sh '''
                    docker --version
                '''
            }
        }
    }
}
