pipeline {
    agent any


    environment {
        IMAGE_TAG = 'koduro/server'
        IMAGE_VERSION = 'latest'
    }

    stages {
        stage('Test') {
            steps {
                echo 'Test to see if the docker file exists'
                sh 'test -f project1/Dockerfile'
            }
        }
        stage('Build') {
            steps {
                sh '''
                    docker --version
                    docker build -t $IMAGE_TAG:$IMAGE_VERSION ./project1
                '''
            }
        }
    }
}
